apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubia
  name: kubia
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32281
    port: 8090
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubia
  type: LoadBalancer
