apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: kubia
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia
        name: kubia
