apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: devops-secret
spec:
  serviceAccountName: pod-service-account
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /tmp/hoge
          name: secret
      envFrom:
        - secretRef:
            name: secret
  volumes:
    - name: secret
      secret:
        secretName: secret
        items:
          - key: foo
            path: foodayo
