apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
#      subPath: myconfig.conf
    - name: certs
      mountPath: /etc/nginx/certs/
    ports:
    - containerPort: 80
      protocol: TCP
    envFrom:
      - configMapRef:
          name: nginx-config
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
      items:
      - key: my-nginx-config.conf
        path: gzip.conf
  - name: certs
    secret:
      secretName: https

